Repository transparency-dev/tesseract, pull requests merged in 2025-06, with the labels that each got.

#349 Add serial offset flag to hammer
  internal/hammer/hammer.go
Labels: enhancement

#333 Enable publication awaiter option in AWS and GCP
  cmd/aws/main.go
  cmd/gcp/main.go
  docs/performance.md
  internal/ct/handlers_test.go
  storage/storage.go
Labels: enhancement

#389 Non a cloud architecture explainer, and documentation index.
  README.md
  docs/README.md
  docs/architecture/NONCLOUD.md
Labels: documentation

#390 Migrate arche2025h1 to MIG
  deployment/live/gcp/static-ct-staging/logs/arche2025h1/terragrunt.hcl
Labels: enhancement

#391 Nits: Few fixes
  deployment/modules/gcp/cloudrun/README.md
  deployment/modules/gcp/tesseract/vm/variables.tf
Labels: documentation

#397 Fix collating logic
  cmd/fsck/main.go
Labels: bug

#394 Bump tessera to e804d187e543794a034317dec8364d206e1f15f2
  go.mod
  go.sum
Labels: dependencies

#398 Fallback to fetching full tiles/bundles if the partial is not present
  internal/client/client.go
  internal/client/client_test.go
Labels: enhancement
