Repository transparency-dev/tesseract, pull requests merged in 2025-04, with the labels that each got.

#228 Add AWS performance doc
  docs/performance.md
Labels: documentation

#242 Bump Tessera & switch to OpenTelemetry
  cmd/aws/main.go
  cmd/gcp/main.go
  cmd/gcp/otel.go
  ctlog.go
  go.mod
  go.sum
  internal/otel/cast.go
  internal/scti/handlers.go
  internal/scti/handlers_test.go
  internal/scti/otel.go
  storage/otel.go
  storage/storage.go
Labels: enhancement, dependencies

#266 Bump Tessera
  go.mod
  go.sum
Labels: dependencies

#269 Bump Tessera to HEAD
  go.mod
  go.sum
Labels: dependencies

#274 Bump Tessera to HEAD
  go.mod
  go.sum
Labels: dependencies

#275 Test that pre-intermediates can issue end cert
  internal/ct/chain_validation_test.go
  internal/testdata/certificates.go
Labels: enhancement

#279 Bump Tessera to HEAD
  go.mod
  go.sum
Labels: dependencies

#280 Bump Tessera
  go.mod
  go.sum
Labels: dependencies
