Repository transparency-dev/tesseract, pull requests merged in 2025-07, with the labels that each got.

#412 Add experimental POSIX CT server
  README.md
  cmd/experimental/posix/README.md
  cmd/experimental/posix/main.go
  storage/posix/file_ops.go
  storage/posix/issuers.go
Labels: enhancement

#418 Bump tessera to 72b3ec8dfeeb557e30f908f7a04141355b025380
  go.mod
  go.sum
Labels: dependencies

#420 [preloader] more submission thread
  deployment/modules/gcp/gce/preloader/main.tf
Labels: enhancement

#431 tesseRact
  .github/workflows/aws_conformance_ci.yml
Labels: bug

#436 Add Scorecards
  .github/workflows/scorecard.yml
  README.md
Labels: github_actions

#445 Limit the number of duplicate requests in flight
  cmd/experimental/posix/main.go
  cmd/tesseract/aws/main.go
  cmd/tesseract/gcp/main.go
  internal/ct/handlers_test.go
  storage/storage.go
Labels: enhancement

#458 Bump tessera to 83493470ded2e200dd652d0b637220ef504db9d6
  go.mod
  go.sum
Labels: dependencies

#466 Add GCP managed instance group performance
  docs/assets/gcp/mig-n2-standard-4-cloud-spanner-200pu/cloud-spanner-total-cpu-utilization.png
  docs/assets/gcp/mig-n2-standard-4-cloud-spanner-200pu/vm-cpu-utilization.png
  docs/performance.md
Labels: documentation

#470 Add some POSIX performance numbers
  docs/performance.md
Labels: documentation

#472 Add GCP managed instance group performance
  docs/assets/gcp/mig-n2-standard-4-x1-cloud-spanner-100pu/cloud-spanner-total-cpu-utilization.png
  docs/assets/gcp/mig-n2-standard-4-x1-cloud-spanner-100pu/vm-cpu-utilization.png
  docs/assets/gcp/mig-n2-standard-4-x3-cloud-spanner-200pu/cloud-spanner-total-cpu-utilization.png
  docs/assets/gcp/mig-n2-standard-4-x3-cloud-spanner-200pu/vm-cpu-utilization.png
  docs/performance.md
Labels: documentation

#482 Enable OTEL metrics in POSIX binary
  cmd/tesseract/posix/main.go
  cmd/tesseract/posix/otel.go
  go.mod
  go.sum
Labels: enhancement
